name: Playwright reporting

on: [push]

jobs:
  reporting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup dependencies
        run: npm i

      - name: Playwright browser updates
        run: npx playwright install

      - name: Run tests
        run: npx playwright test --grep "${{ github.event.inputs.grep }}"
        env:
          TESTOMATIO: '${{ secrets.TESTOMATIO }}'
          TESTOMATIO_RUN: '${{ github.event.inputs.run }}'

      - name: Upload Playwright test results to Testomatio
        if: success() || failure()
        run: |
          npx @testomatio/reporter --path test-results/
        env:
          TESTOMATIO: '${{ secrets.TESTOMATIO }}'
          TESTOMATIO_RUN: '${{ github.event.inputs.run }}'

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf summary test-results/ctrf-report.json

      - name: Publish CTRF Detailed Test Summary Results
        run: npx github-actions-ctrf tests test-results/ctrf-report.json

      - name: Publish CTRF Failed Test Summary Results
        run: npx github-actions-ctrf failed test-results/ctrf-report.json

      - name: Publish CTRF Flaky Test Summary Results
        run: npx github-actions-ctrf flaky test-results/ctrf-report.json

      - name: Annotate failed tests
        run: npx github-actions-ctrf annotate test-results/ctrf-report.json
